# Use the official Node.js base image
FROM node:18.16.1

# Set the working directory in the container
WORKDIR /app

# Copy the frontend code
COPY frontend .

# Install the frontend dependencies
RUN npm install

# Build the frontend
RUN npm run build

# Expose the frontend port
EXPOSE 5173

# Run the frontend server
CMD ["npm", "run", "dev", "--", "--host"]