version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app/
    ports:
      - '8001:8000'
    restart: always
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '5173:5173'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'
